// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, getApiKeyMetadata, getApiKeysCount,
  createApiKey, updateApiKey, updateApiKeyPermissions, regenerateApiKey,
  deleteApiKey, validateApiKey, maskStoredApiKey, isNoLogApiKey, invalidateNoLogCache,
  getAllKeyGroups, getKeyGroup, getKeyGroupWithPermissions,
  createKeyGroup, updateKeyGroup, deleteKeyGroup,
  getGroupPermissions, addGroupPermission, removeGroupPermission, clearGroupPermissions,
  getGroupMembers, getKeyGroupsForApiKey, addKeyToGroup, removeKeyFromGroup,
  checkKeyModelAccess,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  getModelTestResult,
  getModelTestResultsByProvider,
  setModelTestResult,
  deleteModelTestResult,
  clearModelTestResultsByProvider,
  exportDb, importDb,
} from "@/lib/db/index.js";
