export default {
  id: "agy",
  alias: "agy",
  // Duplicate of the canonical card / no connect handler yet - hidden from UI
  hasFree: true,
  display: {
    name: "Antigravity CLI",
    icon: "terminal",
    color: "#F59E0B",
    textIcon: "AGY",
    website: "https://antigravity.google",
  },
  category: "oauth",
  authHint: "Import your Antigravity CLI (`agy`) login (paste/upload its token file), auto-detect a local CLI login, or sign in with Google. Shares the Antigravity backend (incl. Claude models).",
  transport: {
    baseUrls: [
      "https://daily-cloudcode-pa.googleapis.com",
      "https://cloudcode-pa.googleapis.com",
    ],
    format: "antigravity",
    authType: "oauth",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
    headers: {
      "Content-Type": "application/json",
      "User-Agent": "antigravity/cli/1.1.5 (aidev_client; os_type=darwin; arch=arm64; auth_method=consumer)",
    },
  },
  oauth: {
    clientId: "1071006060591-tmhssin2h21lcre235vtolojh4g403ep.apps.googleusercontent.com",
    clientSecret: "REPLACE_WITH_YOUR_GOOGLE_CLIENT_SECRET",
  },
  models: [
    {
      id: "gemini-3.6-flash-high",
      name: "Gemini 3.6 Flash (High)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "gemini-3.6-flash-medium",
      name: "Gemini 3.6 Flash (Medium)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "gemini-3.6-flash-low",
      name: "Gemini 3.6 Flash (Low)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "claude-opus-4-6-thinking",
      name: "Claude Opus 4.6 (Thinking)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6 (Thinking)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "gemini-pro-agent",
      name: "Gemini 3.1 Pro (High)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65535,
      contextLength: 1048576,
    },
    {
      id: "gemini-3.1-pro-low",
      name: "Gemini 3.1 Pro (Low)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65535,
      contextLength: 1048576,
    },
    {
      id: "gemini-3-flash-agent",
      name: "Gemini 3.5 Flash (High)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "gemini-3.5-flash-low",
      name: "Gemini 3.5 Flash (Medium)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "gemini-3.5-flash-extra-low",
      name: "Gemini 3.5 Flash (Low)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "gemini-3.1-flash-lite",
      name: "Gemini 3.1 Flash Lite",
      toolCalling: true,
      maxOutputTokens: 65535,
      contextLength: 1048576,
    },
    {
      id: "gemini-2.5-flash-thinking",
      name: "Gemini 2.5 Flash Thinking",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 65535,
      contextLength: 1048576,
    },
    {
      id: "gemini-2.5-flash",
      name: "Gemini 2.5 Flash",
      toolCalling: true,
      maxOutputTokens: 65535,
      contextLength: 1048576,
    },
    {
      id: "gemini-2.5-flash-lite",
      name: "Gemini 2.5 Flash Lite",
      toolCalling: true,
      maxOutputTokens: 65535,
      contextLength: 1048576,
    },
    {
      id: "gpt-oss-120b-medium",
      name: "GPT-OSS 120B (Medium)",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 131072,
    },
  ],
  passthroughModels: true,
};
