export default {
  id: "command-code",
  alias: "cmd",
  display: {
    name: "Command Code",
    icon: "terminal",
    color: "#111827",
    textIcon: "CC",
    website: "https://commandcode.ai/",
  },
  category: "apikey",
  authHint: "Use a Command Code API key. Requests are sent to Command Code's /alpha/generate endpoint.",
  transport: {
    baseUrl: "https://api.commandcode.ai",
    chatPath: "/alpha/generate",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
    modelsFetcher: {
      url: "https://api.commandcode.ai/provider/v1/models",
      type: "openai",
    },
  },
  models: [
    {
      id: "claude-opus-4-7",
      name: "Claude Opus 4.7 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 32000,
      contextLength: 200000,
    },
    {
      id: "claude-opus-4-6",
      name: "Claude Opus 4.6 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 32000,
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-4-6",
      name: "Claude Sonnet 4.6 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 16384,
      contextLength: 200000,
    },
    {
      id: "claude-haiku-4-5-20251001",
      name: "Claude Haiku 4.5 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 8192,
      contextLength: 200000,
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 128000,
      contextLength: 256000,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 128000,
      contextLength: 256000,
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3 Codex (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 128000,
      contextLength: 256000,
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 Mini (CC)",
      supportsReasoning: false,
      supportsVision: true,
      maxOutputTokens: 128000,
      contextLength: 256000,
    },
    {
      id: "deepseek/deepseek-v4-pro",
      name: "DeepSeek V4 Pro (CC)",
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 1000000,
    },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash (CC)",
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 1000000,
    },
    {
      id: "moonshotai/Kimi-K2.6",
      name: "Kimi K2.6 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 262144,
    },
    {
      id: "moonshotai/Kimi-K2.5",
      name: "Kimi K2.5 (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 262144,
    },
    {
      id: "zai-org/GLM-5.1",
      name: "GLM-5.1 (CC)",
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 200000,
    },
    {
      id: "zai-org/GLM-5",
      name: "GLM-5 (CC)",
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 200000,
    },
    {
      id: "MiniMaxAI/MiniMax-M2.7",
      name: "MiniMax M2.7 (CC)",
      supportsReasoning: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "MiniMaxAI/MiniMax-M2.5",
      name: "MiniMax M2.5 (CC)",
      supportsReasoning: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "Qwen/Qwen3.6-Max-Preview",
      name: "Qwen 3.6 Max (CC)",
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 1000000,
    },
    {
      id: "Qwen/Qwen3.6-Plus",
      name: "Qwen 3.6 Plus (CC)",
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 32768,
      contextLength: 1000000,
    },
  ],
};
