export default {
  id: "ghe-copilot",
  alias: "ghe-copilot",
  display: {
    name: "GitHub Enterprise Copilot",
    icon: "code",
    color: "#10B981",
    website: "https://github.com",
  },
  category: "oauth",
  authHint: "Enter your GHE instance URL (e.g., https://ghe.company.com) in provider settings, then authenticate via device flow.",
  transport: {
    baseUrl: "https://api.githubcopilot.com/chat/completions",
    responsesUrl: "https://api.githubcopilot.com/responses",
    messagesUrl: "https://api.githubcopilot.com/v1/messages",
    authType: "oauth",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
    forceStream: true,
    headers: {
      "copilot-integration-id": "vscode-chat",
      "editor-version": "vscode/1.126.0",
      "editor-plugin-version": "copilot-chat/0.54.0",
      "user-agent": "GitHubCopilotChat/0.54.0",
      "openai-intent": "conversation-panel",
      "x-github-api-version": "2026-06-01",
      "x-vscode-user-agent-library-version": "electron-fetch",
      "X-Initiator": "user",
      Accept: "application/json",
      "Content-Type": "application/json",
    },
  },
  oauth: {
    clientId: "Iv1.b507a08c87ecfe98",
  },
  models: [
    {
      id: "claude-fable-5",
      name: "Claude Fable 5",
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
    {
      id: "claude-opus-5",
      name: "Claude Opus 5",
      maxOutputTokens: 64000,
      unsupportedParams: [
        "temperature",
        "top_p",
        "top_k",
      ],
      contextLength: 1000000,
    },
    {
      id: "claude-opus-4.8-fast",
      name: "Claude Opus 4.8 (fast mode)",
      maxOutputTokens: 64000,
      unsupportedParams: [
        "temperature",
        "top_p",
        "top_k",
      ],
      contextLength: 1000000,
    },
    {
      id: "claude-opus-4.8",
      name: "Claude Opus 4.8",
      maxOutputTokens: 64000,
      unsupportedParams: [
        "temperature",
        "top_p",
        "top_k",
      ],
      contextLength: 1000000,
    },
    {
      id: "claude-opus-4.7",
      name: "Claude Opus 4.7",
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
    {
      id: "claude-sonnet-4.6",
      name: "Claude Sonnet 4.6",
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
    {
      id: "claude-opus-4.5",
      name: "Claude Opus 4.5",
      maxOutputTokens: 32000,
      contextLength: 200000,
    },
    {
      id: "claude-sonnet-5",
      name: "Claude Sonnet 5",
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
    {
      id: "claude-sonnet-4.5",
      name: "Claude Sonnet 4.5",
      maxOutputTokens: 32000,
      contextLength: 200000,
    },
    {
      id: "claude-haiku-4.5",
      name: "Claude Haiku 4.5",
      maxOutputTokens: 32000,
      contextLength: 200000,
    },
    {
      id: "gemini-3.1-pro-preview",
      name: "Gemini 3.1 Pro",
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
    {
      id: "gemini-3.5-flash",
      name: "Gemini 3.5 Flash",
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 128000,
    },
    {
      id: "gpt-5.6-terra",
      name: "GPT-5.6 Terra",
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 128000,
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6 Luna",
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 128000,
    },
    {
      id: "gpt-5.5",
      name: "GPT-5.5",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsXHighEffort: true,
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 1050000,
    },
    {
      id: "gpt-5.4",
      name: "GPT-5.4",
      supportsXHighEffort: true,
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 1050000,
    },
    {
      id: "gpt-5.4-mini",
      name: "GPT-5.4 mini",
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 400000,
    },
    {
      id: "gpt-5.3-codex",
      name: "GPT-5.3-Codex",
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 400000,
    },
    {
      id: "gpt-5-mini",
      name: "GPT-5 mini",
      maxOutputTokens: 64000,
      targetFormat: "openai-responses",
      contextLength: 264000,
    },
    {
      id: "gpt-4o-2024-11-20",
      name: "GPT-4o",
      maxOutputTokens: 16384,
      contextLength: 128000,
    },
    {
      id: "gpt-4o-mini",
      name: "GPT-4o mini",
      maxOutputTokens: 4096,
      contextLength: 128000,
    },
    {
      id: "gpt-4-0125-preview",
      name: "GPT 4 Turbo",
      maxOutputTokens: 4096,
      contextLength: 128000,
    },
    {
      id: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      maxOutputTokens: 32000,
      contextLength: 256000,
    },
    {
      id: "mai-code-1-flash",
      name: "MAI-Code-1-Flash",
      maxOutputTokens: 128000,
      targetFormat: "openai-responses",
      contextLength: 256000,
    },
    {
      id: "oswe-vscode-prime",
      name: "Raptor mini",
      maxOutputTokens: 64000,
      targetFormat: "openai-responses",
      contextLength: 264000,
    },
  ],
};
