export default {
  id: "glmt",
  alias: "glmt",
  display: {
    name: "GLM Thinking",
    icon: "psychology",
    color: "#1D4ED8",
    textIcon: "GT",
    website: "https://open.bigmodel.cn",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.z.ai/api/coding/paas/v4/chat/completions",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
    timeoutMs: 900000,
  },
  models: [
    {
      id: "glm-5.2",
      name: "GLM 5.2",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 1000000,
    },
    {
      id: "glm-5.2-high",
      name: "GLM 5.2 High",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 1000000,
    },
    {
      id: "glm-5.2-max",
      name: "GLM 5.2 Max",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 1000000,
    },
    {
      id: "glm-5.1",
      name: "GLM 5.1",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 204800,
    },
    {
      id: "glm-5",
      name: "GLM 5",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 200000,
    },
    {
      id: "glm-5-turbo",
      name: "GLM 5 Turbo",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 200000,
    },
    {
      id: "glm-4.7-flash",
      name: "GLM 4.7 Flash",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 200000,
    },
    {
      id: "glm-4.7",
      name: "GLM 4.7",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 131072,
      contextLength: 200000,
    },
    {
      id: "glm-4.6v",
      name: "GLM 4.6V (Vision)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 32768,
      contextLength: 128000,
    },
    {
      id: "glm-4.6",
      name: "GLM 4.6",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 200000,
    },
    {
      id: "glm-4.5v",
      name: "GLM 4.5V (Vision)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 32768,
      contextLength: 16000,
    },
    {
      id: "glm-4.5",
      name: "GLM 4.5",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 128000,
    },
    {
      id: "glm-4.5-air",
      name: "GLM 4.5 Air",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 32768,
      contextLength: 128000,
    },
  ],
};
