// Auto-generated by scripts/generate-registry-index.mjs — do not edit by hand.
// Run: node scripts/generate-registry-index.mjs
import p0 from "./adapta-web.js";
import p1 from "./adobe-firefly.js";
import p2 from "./agentrouter.js";
import p3 from "./agnes.js";
import p4 from "./agy.js";
import p5 from "./ai21.js";
import p6 from "./aihorde.js";
import p7 from "./aimlapi.js";
import p8 from "./ainative.js";
import p9 from "./aion.js";
import p10 from "./alibaba-cn.js";
import p11 from "./alibaba.js";
import p12 from "./alicode-intl.js";
import p13 from "./alicode.js";
import p14 from "./alims-intl.js";
import p15 from "./amazon-q.js";
import p16 from "./ant-ling.js";
import p17 from "./anthropic.js";
import p18 from "./antigravity.js";
import p19 from "./anyapi.js";
import p20 from "./api-airforce.js";
import p21 from "./askcodi.js";
import p22 from "./assemblyai.js";
import p23 from "./auggie.js";
import p24 from "./auriko.js";
import p25 from "./aws-polly.js";
import p26 from "./azure.js";
import p27 from "./bai.js";
import p28 from "./baichuan.js";
import p29 from "./baidu.js";
import p30 from "./bailian-coding-plan.js";
import p31 from "./baseten.js";
import p32 from "./bazaarlink.js";
import p33 from "./bedrock.js";
import p34 from "./black-forest-labs.js";
import p35 from "./blackbox-web.js";
import p36 from "./blackbox.js";
import p37 from "./bluesminds.js";
import p38 from "./brave-search.js";
import p39 from "./byteplus.js";
import p40 from "./bytez.js";
import p41 from "./cartesia.js";
import p42 from "./cerebras.js";
import p43 from "./charm-hyper.js";
import p44 from "./chat-oripe.js";
import p45 from "./chatanywhere.js";
import p46 from "./chatgpt-web-codex.js";
import p47 from "./chatgpt-web.js";
import p48 from "./cheaperinference.js";
import p49 from "./chenzk.js";
import p50 from "./chipotle.js";
import p51 from "./chutes.js";
import p52 from "./claude-web.js";
import p53 from "./claude.js";
import p54 from "./cline.js";
import p55 from "./clinepass.js";
import p56 from "./cloudcode-one.js";
import p57 from "./cloudflare-ai.js";
import p58 from "./clova-studio.js";
import p59 from "./codebuddy-cn.js";
import p60 from "./codebuddy-intl.js";
import p61 from "./codestral.js";
import p62 from "./codex-cloud.js";
import p63 from "./codex.js";
import p64 from "./cohere.js";
import p65 from "./comfyui.js";
import p66 from "./command-code.js";
import p67 from "./commandcode.js";
import p68 from "./conol-web.js";
import p69 from "./copilot-m365-web.js";
import p70 from "./copilot-web.js";
import p71 from "./coqui.js";
import p72 from "./coze.js";
import p73 from "./crof.js";
import p74 from "./cursor.js";
import p75 from "./dahl.js";
import p76 from "./databricks.js";
import p77 from "./deepai.js";
import p78 from "./deepgram.js";
import p79 from "./deepinfra.js";
import p80 from "./deepseek-web.js";
import p81 from "./deepseek.js";
import p82 from "./devin-cli-agentic.js";
import p83 from "./devin-cli.js";
import p84 from "./devin-desktop.js";
import p85 from "./devin.js";
import p86 from "./dgrid.js";
import p87 from "./dify.js";
import p88 from "./digitalocean.js";
import p89 from "./dit.js";
import p90 from "./docker-model-runner.js";
import p91 from "./doteb.js";
import p92 from "./doubao-web.js";
import p93 from "./doubao.js";
import p94 from "./duckduckgo-web.js";
import p95 from "./dxnt.js";
import p96 from "./edge-tts.js";
import p97 from "./electronhub.js";
import p98 from "./elevenlabs.js";
import p99 from "./exa.js";
import p100 from "./factory.js";
import p101 from "./fal-ai.js";
import p102 from "./fastrouter.js";
import p103 from "./featherless.js";
import p104 from "./felo-web.js";
import p105 from "./fim-gate.js";
import p106 from "./firecrawl.js";
import p107 from "./fireworks.js";
import p108 from "./fishaudio.js";
import p109 from "./free-ai.js";
import p110 from "./freeaiapikey.js";
import p111 from "./freeinference.js";
import p112 from "./freemodel-dev.js";
import p113 from "./freetheai.js";
import p114 from "./friendli.js";
import p115 from "./friendliai.js";
import p116 from "./g0i.js";
import p117 from "./g4f-gemini.js";
import p118 from "./g4f-groq.js";
import p119 from "./g4f-nvidia.js";
import p120 from "./g4f-ollama.js";
import p121 from "./g4f-pollinations.js";
import p122 from "./galadriel.js";
import p123 from "./gemini-business.js";
import p124 from "./gemini-cli.js";
import p125 from "./gemini-web.js";
import p126 from "./gemini.js";
import p127 from "./ghe-copilot.js";
import p128 from "./gigachat.js";
import p129 from "./github.js";
import p130 from "./gitlab-duo.js";
import p131 from "./gitlab.js";
import p132 from "./gitlawb-gmi.js";
import p133 from "./gitlawb.js";
import p134 from "./gladia.js";
import p135 from "./glhf.js";
import p136 from "./glm-cn.js";
import p137 from "./glm.js";
import p138 from "./glmt.js";
import p139 from "./google-pse.js";
import p140 from "./google-tts.js";
import p141 from "./grok-cli.js";
import p142 from "./grok-web.js";
import p143 from "./groq.js";
import p144 from "./hackclub.js";
import p145 from "./hailuo-web.js";
import p146 from "./haiper.js";
import p147 from "./hcap.js";
import p148 from "./hcnsec.js";
import p149 from "./helixmind.js";
import p150 from "./helyxai.js";
import p151 from "./heroku.js";
import p152 from "./hetzner.js";
import p153 from "./huggingchat.js";
import p154 from "./huggingface.js";
import p155 from "./hyperagent.js";
import p156 from "./hyperbolic.js";
import p157 from "./ideogram.js";
import p158 from "./iflow.js";
import p159 from "./iflytek.js";
import p160 from "./inception.js";
import p161 from "./inference-net.js";
import p162 from "./inner-ai.js";
import p163 from "./internlm.js";
import p164 from "./inworld.js";
import p165 from "./jbridge.js";
import p166 from "./jina-ai.js";
import p167 from "./jina-reader.js";
import p168 from "./jules.js";
import p169 from "./kenari.js";
import p170 from "./kie.js";
import p171 from "./kilo-gateway.js";
import p172 from "./kilo.js";
import p173 from "./kilocode.js";
import p174 from "./kimchi.js";
import p175 from "./kimetsu.js";
import p176 from "./kimi-coding-apikey.js";
import p177 from "./kimi-coding.js";
import p178 from "./kimi-web.js";
import p179 from "./kimi.js";
import p180 from "./kiro.js";
import p181 from "./kunavo.js";
import p182 from "./lambda-ai.js";
import p183 from "./lemonade.js";
import p184 from "./leonardo.js";
import p185 from "./linkup-search.js";
import p186 from "./linkup.js";
import p187 from "./liquid.js";
import p188 from "./literouter.js";
import p189 from "./llama-cpp.js";
import p190 from "./llamacpp-local.js";
import p191 from "./llamafile.js";
import p192 from "./llamagate.js";
import p193 from "./llm-kiwi.js";
import p194 from "./llm7.js";
import p195 from "./llmai.js";
import p196 from "./llmgateway.js";
import p197 from "./llmrelay.js";
import p198 from "./lm-studio-local.js";
import p199 from "./lmarena.js";
import p200 from "./local-device.js";
import p201 from "./longcat.js";
import p202 from "./maritalk.js";
import p203 from "./meganova-ai.js";
import p204 from "./meta-llama.js";
import p205 from "./microsoft-designer-web.js";
import p206 from "./mimo-free.js";
import p207 from "./mimocode.js";
import p208 from "./minimax-cn.js";
import p209 from "./minimax.js";
import p210 from "./mistral.js";
import p211 from "./mixedbread.js";
import p212 from "./mixlayer.js";
import p213 from "./mnn-ai.js";
import p214 from "./mnn.js";
import p215 from "./modal.js";
import p216 from "./modelscope.js";
import p217 from "./monsterapi.js";
import p218 from "./moonshot.js";
import p219 from "./morph.js";
import p220 from "./muse-code.js";
import p221 from "./muse-spark-web.js";
import p222 from "./naga-ac.js";
import p223 from "./naga-ai.js";
import p224 from "./nagaai.js";
import p225 from "./nanobanana.js";
import p226 from "./nanogpt.js";
import p227 from "./nara.js";
import p228 from "./navy.js";
import p229 from "./navyapi.js";
import p230 from "./nebius.js";
import p231 from "./nlpcloud.js";
import p232 from "./nomic.js";
import p233 from "./notion-web.js";
import p234 from "./nous-research.js";
import p235 from "./novita.js";
import p236 from "./nscale.js";
import p237 from "./nube.js";
import p238 from "./nvidia.js";
import p239 from "./oci.js";
import p240 from "./ofoxai.js";
import p241 from "./ollama-cloud.js";
import p242 from "./ollama-local.js";
import p243 from "./ollama-search.js";
import p244 from "./ollama.js";
import p245 from "./oobabooga.js";
import p246 from "./openadapter.js";
import p247 from "./openai.js";
import p248 from "./opencode-go.js";
import p249 from "./opencode-zen.js";
import p250 from "./opencode.js";
import p251 from "./openference-api.js";
import p252 from "./openference.js";
import p253 from "./openrouter.js";
import p254 from "./openvecta.js";
import p255 from "./orcarouter.js";
import p256 from "./ovhcloud.js";
import p257 from "./perplexity-agent.js";
import p258 from "./perplexity-web.js";
import p259 from "./perplexity.js";
import p260 from "./pioneer.js";
import p261 from "./plamo.js";
import p262 from "./playht.js";
import p263 from "./poe-web.js";
import p264 from "./poe.js";
import p265 from "./poixe-ai.js";
import p266 from "./pollinations.js";
import p267 from "./poolside.js";
import p268 from "./portkey.js";
import p269 from "./predibase.js";
import p270 from "./promptql.js";
import p271 from "./publicai.js";
import p272 from "./qiniu.js";
import p273 from "./qoder.js";
import p274 from "./qwen-cloud-token-plan.js";
import p275 from "./qwen-cloud.js";
import p276 from "./qwen-web.js";
import p277 from "./raycast.js";
import p278 from "./recraft.js";
import p279 from "./regolo.js";
import p280 from "./reka.js";
import p281 from "./requesty.js";
import p282 from "./rev-ai.js";
import p283 from "./routeway.js";
import p284 from "./routra.js";
import p285 from "./runwayml.js";
import p286 from "./sambanova.js";
import p287 from "./sarvam.js";
import p288 from "./scaleway.js";
import p289 from "./sdwebui.js";
import p290 from "./sealion.js";
import p291 from "./searchapi.js";
import p292 from "./searxng.js";
import p293 from "./selfhosted-embedding.js";
import p294 from "./selfhosted-stt.js";
import p295 from "./selfhosted-tts.js";
import p296 from "./sensenova.js";
import p297 from "./serper.js";
import p298 from "./siliconflow.js";
import p299 from "./snowflake.js";
import p300 from "./soniox.js";
import p301 from "./sparkdesk.js";
import p302 from "./speechmatics.js";
import p303 from "./speka.js";
import p304 from "./stability-ai.js";
import p305 from "./stepfun.js";
import p306 from "./sumopod.js";
import p307 from "./suno.js";
import p308 from "./synthetic.js";
import p309 from "./t3-web.js";
import p310 from "./tavily.js";
import p311 from "./tencent.js";
import p312 from "./theoldllm.js";
import p313 from "./tinycms-web.js";
import p314 from "./together.js";
import p315 from "./tokenreply.js";
import p316 from "./tokenrouter.js";
import p317 from "./topaz.js";
import p318 from "./tortoise.js";
import p319 from "./trae.js";
import p320 from "./triton.js";
import p321 from "./typhoon.js";
import p322 from "./uai.js";
import p323 from "./udio.js";
import p324 from "./uncloseai.js";
import p325 from "./unorouter.js";
import p326 from "./upstage.js";
import p327 from "./v0-vercel-web.js";
import p328 from "./v0-vercel.js";
import p329 from "./venice-web.js";
import p330 from "./venice.js";
import p331 from "./veoaifree-web.js";
import p332 from "./vercel-ai-gateway.js";
import p333 from "./vertex-partner.js";
import p334 from "./vertex.js";
import p335 from "./vllm.js";
import p336 from "./void-ai.js";
import p337 from "./voidai.js";
import p338 from "./volcengine-ark.js";
import p339 from "./volcengine.js";
import p340 from "./volta.js";
import p341 from "./voyage-ai.js";
import p342 from "./wafer.js";
import p343 from "./wandb.js";
import p344 from "./watsonx.js";
import p345 from "./windsurf.js";
import p346 from "./writer.js";
import p347 from "./x5lab.js";
import p348 from "./xai-oauth.js";
import p349 from "./xai.js";
import p350 from "./xiaomi-mimo-token-plan.js";
import p351 from "./xiaomi-mimo.js";
import p352 from "./xiaomi-tokenplan.js";
import p353 from "./xinference.js";
import p354 from "./yi.js";
import p355 from "./yolo-auto.js";
import p356 from "./youcom.js";
import p357 from "./yuanbao-web.js";
import p358 from "./zai-web.js";
import p359 from "./zai.js";
import p360 from "./zanityai.js";
import p361 from "./zed-hosted.js";
import p362 from "./zed.js";
import p363 from "./zenmux-free.js";
import p364 from "./zenmux.js";
import p365 from "./zerolimitai.js";
import p366 from "./zukijourney.js";
import p367 from "./zylo-api.js";

export default [
  p0,
  p1,
  p2,
  p3,
  p4,
  p5,
  p6,
  p7,
  p8,
  p9,
  p10,
  p11,
  p12,
  p13,
  p14,
  p15,
  p16,
  p17,
  p18,
  p19,
  p20,
  p21,
  p22,
  p23,
  p24,
  p25,
  p26,
  p27,
  p28,
  p29,
  p30,
  p31,
  p32,
  p33,
  p34,
  p35,
  p36,
  p37,
  p38,
  p39,
  p40,
  p41,
  p42,
  p43,
  p44,
  p45,
  p46,
  p47,
  p48,
  p49,
  p50,
  p51,
  p52,
  p53,
  p54,
  p55,
  p56,
  p57,
  p58,
  p59,
  p60,
  p61,
  p62,
  p63,
  p64,
  p65,
  p66,
  p67,
  p68,
  p69,
  p70,
  p71,
  p72,
  p73,
  p74,
  p75,
  p76,
  p77,
  p78,
  p79,
  p80,
  p81,
  p82,
  p83,
  p84,
  p85,
  p86,
  p87,
  p88,
  p89,
  p90,
  p91,
  p92,
  p93,
  p94,
  p95,
  p96,
  p97,
  p98,
  p99,
  p100,
  p101,
  p102,
  p103,
  p104,
  p105,
  p106,
  p107,
  p108,
  p109,
  p110,
  p111,
  p112,
  p113,
  p114,
  p115,
  p116,
  p117,
  p118,
  p119,
  p120,
  p121,
  p122,
  p123,
  p124,
  p125,
  p126,
  p127,
  p128,
  p129,
  p130,
  p131,
  p132,
  p133,
  p134,
  p135,
  p136,
  p137,
  p138,
  p139,
  p140,
  p141,
  p142,
  p143,
  p144,
  p145,
  p146,
  p147,
  p148,
  p149,
  p150,
  p151,
  p152,
  p153,
  p154,
  p155,
  p156,
  p157,
  p158,
  p159,
  p160,
  p161,
  p162,
  p163,
  p164,
  p165,
  p166,
  p167,
  p168,
  p169,
  p170,
  p171,
  p172,
  p173,
  p174,
  p175,
  p176,
  p177,
  p178,
  p179,
  p180,
  p181,
  p182,
  p183,
  p184,
  p185,
  p186,
  p187,
  p188,
  p189,
  p190,
  p191,
  p192,
  p193,
  p194,
  p195,
  p196,
  p197,
  p198,
  p199,
  p200,
  p201,
  p202,
  p203,
  p204,
  p205,
  p206,
  p207,
  p208,
  p209,
  p210,
  p211,
  p212,
  p213,
  p214,
  p215,
  p216,
  p217,
  p218,
  p219,
  p220,
  p221,
  p222,
  p223,
  p224,
  p225,
  p226,
  p227,
  p228,
  p229,
  p230,
  p231,
  p232,
  p233,
  p234,
  p235,
  p236,
  p237,
  p238,
  p239,
  p240,
  p241,
  p242,
  p243,
  p244,
  p245,
  p246,
  p247,
  p248,
  p249,
  p250,
  p251,
  p252,
  p253,
  p254,
  p255,
  p256,
  p257,
  p258,
  p259,
  p260,
  p261,
  p262,
  p263,
  p264,
  p265,
  p266,
  p267,
  p268,
  p269,
  p270,
  p271,
  p272,
  p273,
  p274,
  p275,
  p276,
  p277,
  p278,
  p279,
  p280,
  p281,
  p282,
  p283,
  p284,
  p285,
  p286,
  p287,
  p288,
  p289,
  p290,
  p291,
  p292,
  p293,
  p294,
  p295,
  p296,
  p297,
  p298,
  p299,
  p300,
  p301,
  p302,
  p303,
  p304,
  p305,
  p306,
  p307,
  p308,
  p309,
  p310,
  p311,
  p312,
  p313,
  p314,
  p315,
  p316,
  p317,
  p318,
  p319,
  p320,
  p321,
  p322,
  p323,
  p324,
  p325,
  p326,
  p327,
  p328,
  p329,
  p330,
  p331,
  p332,
  p333,
  p334,
  p335,
  p336,
  p337,
  p338,
  p339,
  p340,
  p341,
  p342,
  p343,
  p344,
  p345,
  p346,
  p347,
  p348,
  p349,
  p350,
  p351,
  p352,
  p353,
  p354,
  p355,
  p356,
  p357,
  p358,
  p359,
  p360,
  p361,
  p362,
  p363,
  p364,
  p365,
  p366,
  p367,
];
