export default {
  id: "moonshot",
  alias: "moonshot",
  display: {
    name: "Kimi",
    icon: "rocket_launch",
    color: "#1E40AF",
    textIcon: "MS",
    website: "https://platform.kimi.ai?aff=novaroute",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.moonshot.ai/v1/chat/completions",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
  },
  models: [
    {
      id: "kimi-k3",
      name: "Kimi K3",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsXHighEffort: false,
      maxOutputTokens: 1048576,
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
      contextLength: 1048576,
      interleavedField: "reasoning_content",
    },
    {
      id: "kimi-k2.7-code",
      name: "Kimi K2.7 Code",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 262144,
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
      contextLength: 262144,
      interleavedField: "reasoning_content",
    },
    {
      id: "kimi-k2.7-code-highspeed",
      name: "Kimi K2.7 Code (High Speed)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 262144,
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
      contextLength: 262144,
      interleavedField: "reasoning_content",
    },
    {
      id: "kimi-k2.6",
      name: "Kimi K2.6",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 262144,
      unsupportedParams: [
        "temperature",
        "top_p",
        "frequency_penalty",
        "presence_penalty",
        "logprobs",
        "top_logprobs",
        "n",
      ],
      contextLength: 262144,
      interleavedField: "reasoning_content",
    },
  ],
};
