export default {
  id: "muse-code",
  alias: "mc",
  display: {
    name: "Muse Code (Meta)",
    icon: "auto_awesome",
    color: "#0866FF",
    textIcon: "MC",
    website: "https://github.com/meta-llama/llama-stack",
  },
  category: "apikey",
  authHint: "Use your META_API_KEY env var as a Bearer token. Muse Code CLI uses the OpenAI Responses API wire format (POST /responses).",
  transport: {
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
  },
  models: [
    {
      id: "llama-4-maverick",
      name: "Llama 4 Maverick",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsXHighEffort: true,
      maxOutputTokens: 131072,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
        "logitBias",
      ],
      contextLength: 1048576,
    },
    {
      id: "llama-4-scout",
      name: "Llama 4 Scout",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsXHighEffort: true,
      maxOutputTokens: 131072,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
        "logitBias",
      ],
      contextLength: 1048576,
    },
    {
      id: "llama-3.3-70b",
      name: "Llama 3.3 70B",
      toolCalling: true,
      supportsReasoning: false,
      maxOutputTokens: 32768,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
      ],
      contextLength: 131072,
    },
    {
      id: "llama-3.1-405b",
      name: "Llama 3.1 405B",
      toolCalling: true,
      supportsReasoning: false,
      maxOutputTokens: 32768,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
      ],
      contextLength: 131072,
    },
    {
      id: "llama-3.1-70b",
      name: "Llama 3.1 70B",
      toolCalling: true,
      supportsReasoning: false,
      maxOutputTokens: 32768,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
      ],
      contextLength: 131072,
    },
    {
      id: "llama-3.1-8b",
      name: "Llama 3.1 8B",
      toolCalling: true,
      supportsReasoning: false,
      maxOutputTokens: 32768,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
      ],
      contextLength: 131072,
    },
    {
      id: "llama-3.2-90b-vision",
      name: "Llama 3.2 90B Vision",
      toolCalling: true,
      supportsReasoning: false,
      supportsVision: true,
      maxOutputTokens: 32768,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
      ],
      contextLength: 131072,
    },
    {
      id: "llama-3.2-11b-vision",
      name: "Llama 3.2 11B Vision",
      toolCalling: true,
      supportsReasoning: false,
      supportsVision: true,
      maxOutputTokens: 32768,
      targetFormat: "openai-responses",
      unsupportedParams: [
        "logprobs",
        "topLogprobs",
      ],
      contextLength: 131072,
    },
  ],
  passthroughModels: true,
};
