export default {
  id: "orcarouter",
  alias: "orcarouter",
  display: {
    name: "OrcaRouter",
    icon: "router",
    color: "#0891B2",
    textIcon: "ORC",
    website: "https://www.orcarouter.ai",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.orcarouter.ai/v1",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
    headers: {
      "HTTP-Referer": "https://endpoint-proxy.local",
      "X-Title": "Endpoint Proxy",
    },
  },
  models: [
    {
      id: "orcarouter/auto",
      name: "Auto (smart routing)",
      toolCalling: true,
      contextLength: 128000,
    },
    {
      id: "openai/gpt-5.5",
      name: "GPT-5.5",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 128000,
      contextLength: 1050000,
    },
    {
      id: "google/gemini-3.5-flash",
      name: "Gemini 3.5 Flash",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1048576,
    },
    {
      id: "anthropic/claude-opus-4.8",
      name: "Claude Opus 4.8",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 128000,
      contextLength: 1000000,
    },
    {
      id: "grok/grok-4.3",
      name: "Grok 4.3",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1000000,
    },
    {
      id: "deepseek/deepseek-v4-pro",
      name: "DeepSeek V4 Pro",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 384000,
      contextLength: 1048576,
    },
    {
      id: "minimax/minimax-m2.7",
      name: "MiniMax M2.7",
      toolCalling: true,
      supportsReasoning: true,
      maxOutputTokens: 2048,
      contextLength: 204800,
    },
    {
      id: "qwen/qwen3.7-max",
      name: "Qwen3.7 Max",
      toolCalling: true,
      maxOutputTokens: 64000,
      contextLength: 1000000,
    },
  ],
  passthroughModels: true,
};
