export default {
  id: "qwen-web",
  alias: "qwen-web",
  hasFree: true,
  display: {
    name: "Qwen Web (Free)",
    icon: "auto_awesome",
    color: "#10B981",
    textIcon: "QW",
    website: "https://chat.qwen.ai",
  },
  category: "webCookie",
  authHint: "Open chat.qwen.ai, log in, then open DevTools → Application → Local Storage → copy the \"token\" value (or use tongyi_sso_ticket cookie as Bearer token).",
  cookieHint: "Open DevTools → Application → Local Storage → chat.qwen.ai → copy token value",
  transport: {
    baseUrl: "https://chat.qwen.ai/api/v2/chat/completions",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
  },
  models: [
    {
      id: "qwen3.8-max-preview",
      name: "Qwen3.8 Max Preview",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1000000,
    },
    {
      id: "qwen3.7-max",
      name: "Qwen3.7 Max",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: false,
      maxOutputTokens: 65536,
      contextLength: 1000000,
    },
    {
      id: "qwen3.7-plus",
      name: "Qwen3.7 Plus",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1000000,
    },
    {
      id: "qwen3.6-plus",
      name: "Qwen3.6 Plus",
      toolCalling: false,
      supportsReasoning: true,
      supportsVision: true,
      maxOutputTokens: 65536,
      contextLength: 1000000,
    },
  ],
  credentialFields: [
    { id: "token", label: "Token (Bearer)", placeholder: "eyJhbGciOi...", required: true, hint: "DevTools > Application > Local Storage > chat.qwen.ai > token" },
    { id: "tongyi_sso_ticket", label: "tongyi_sso_ticket (optional)", required: false, hint: "Alternative Bearer credential from cookies" },
  ],
};
