export default {
  id: "voidai",
  alias: "voidai",
  hasFree: true,
  display: {
    name: "VoidAI",
    icon: "cloud_queue",
    color: "#1E1E2E",
    textIcon: "VAI",
    website: "https://voidai.app",
  },
  category: "apikey",
  transport: {
    baseUrl: "https://api.voidai.app/v1/chat/completions",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
  },
  models: [
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-5", name: "GPT-5" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "qwen3-235b-a22b", name: "Qwen3 235B" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "umbra", name: "Umbra" },
  ],
  passthroughModels: true,
};
