export default {
  id: "zenmux",
  alias: "zm",
  hasFree: true,
  display: {
    name: "ZenMux",
    icon: "neurology",
    color: "#7C3AED",
    textIcon: "ZM",
    website: "https://zenmux.ai",
  },
  category: "apikey",
  authHint: "Use your ZenMux API key in Authorization: Bearer <key>. ZenMux is fully OpenAI-compatible. Base URL: https://zenmux.ai/api/v1.",
  transport: {
    baseUrl: "https://zenmux.ai/api/v1/chat/completions",
    authType: "apikey",
    auth: {
      header: "Authorization",
      scheme: "bearer",
      combined: true,
    },
    modelsFetcher: {
      url: "https://zenmux.ai/api/v1/models",
      type: "openai",
    },
  },
  models: [
    {
      id: "google/gemini-3.1-pro-preview",
      name: "Gemini 3.1 Pro Preview (ZenMux)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1048576,
    },
    {
      id: "google/gemini-3-flash-preview",
      name: "Gemini 3 Flash Preview (ZenMux)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 1048576,
    },
    {
      id: "openai/gpt-5",
      name: "GPT-5 (ZenMux)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 400000,
    },
    {
      id: "anthropic/claude-sonnet-4.5",
      name: "Claude Sonnet 4.5 (ZenMux)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 200000,
    },
    {
      id: "anthropic/claude-opus-4.5",
      name: "Claude Opus 4.5 (ZenMux)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: true,
      contextLength: 200000,
    },
    {
      id: "deepseek/deepseek-chat",
      name: "DeepSeek V3.2 Chat (ZenMux)",
      toolCalling: true,
      supportsReasoning: false,
      supportsVision: false,
      contextLength: 128000,
    },
    {
      id: "x-ai/grok-4.1-fast",
      name: "Grok 4.1 Fast (ZenMux)",
      toolCalling: true,
      supportsReasoning: true,
      supportsVision: false,
      contextLength: 131072,
    },
    {
      id: "mistralai/mistral-large-2512",
      name: "Mistral Large 2512 (ZenMux)",
      toolCalling: true,
      supportsReasoning: false,
      supportsVision: true,
      contextLength: 128000,
    },
    {
      id: "z-ai/glm-4.6v-flash",
      name: "GLM 4.6V Flash (ZenMux)",
      toolCalling: true,
      supportsReasoning: false,
      supportsVision: true,
      contextLength: 128000,
    },
  ],
};
